# Documentation: https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config

issuers:
  ian-ville:
    name: ian-cille
    abbreviation: ian-ville
    url: https://www.ian-ville.ca/ian-ville-info-page
    email: info@ian-ville.ca
    logo_path: ../assets/img/ian-ville-logo.jpg
    endpoint: $ENDPOINT_URL

    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      sign_target: false

    credential_types:
    - description: The ian-permit credential issued by ian-cille
      schema: ian-registration.ian-ville
      issuer_url: $ENDPOINT_URL/ian-ville/ian-registration
      credential:
        effective_date:
          input: effective_date
          from: claim
        revoked_date:
          input: expiry_date
          from: claim
      topic:
        source_id:
          input: corp_num
          from: claim
        type:
          input: registration
          from: value
      mapping:
      - model: attribute
        fields:
          type:
            input: corp_num
            from: value
          value:
            input: corp_num
            from: claim
      - model: attribute
        fields:
          type:
            input: registration_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: registration_date
            from: claim
      - model: name
        fields:
          text:
            input: entity_name
            from: claim
          type:
            input: entity_name
            from: value
      - model: attribute
        fields:
          type:
            input: entity_name_effective
            from: value
          format:
            input: datetime
            from: value
          value:
            input: entity_name_effective
            from: claim
      - model: address
        fields:
          addressee:
            input: addressee
            from: claim
          civic_address:
            input: address_line_1
            from: claim
          city:
            input: city
            from: claim
          province:
            input: province
            from: claim
          postal_code:
            input: postal_code
            from: claim
          country:
            input: country
            from: claim
      - model: attribute
        fields:
          type:
            input: entity_status
            from: value
          value:
            input: entity_status
            from: claim
      - model: attribute
        fields:
          type:
            input: entity_status_effective
            from: value
          format:
            input: datetime
            from: value
          value:
            input: entity_status_effective
            from: claim
      - model: attribute
        fields:
          type:
            input: entity_type
            from: value
          value:
            input: entity_type
            from: claim
      - model: attribute
        fields:
          type:
            input: registered_jurisdiction
            from: value
          value:
            input: registered_jurisdiction
            from: claim
      - model: attribute
        fields:
          type:
            input: effective_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: effective_date
            from: claim
      - model: attribute
        fields:
          type:
            input: expiry_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: expiry_date
            from: claim
    - description: The ian-permit credential issued by ian-cille
      schema: ian-permit.ian-ville
      issuer_url: $ENDPOINT_URL/ian-ville/ian-permit
      depends_on:
      - greenlight_registration
      credential:
        effective_date:
          input: effective_date
          from: claim
      topic:
        source_id:
          input: corp_num
          from: claim
        type:
          input: registration
          from: value
      mapping:
      - model: attribute
        fields:
          type:
            input: corp_num
            from: value
          value:
            input: corp_num
            from: claim
      - model: name
        fields:
          text:
            input: entity_name
            from: claim
          type:
            input: entity_name
            from: value
      - model: attribute
        fields:
          type:
            input: permit_id
            from: value
          value:
            input: permit_id
            from: claim
      - model: attribute
        fields:
          type:
            input: permit_type
            from: value
          value:
            input: permit_type
            from: claim
      - model: attribute
        fields:
          type:
            input: permit_issued_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: permit_issued_date
            from: claim
      - model: attribute
        fields:
          type:
            input: permit_status
            from: value
          value:
            input: permit_status
            from: claim
      - model: attribute
        fields:
          type:
            input: effective_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: effective_date
            from: claim

verifiers:
  bctob:
    name: BC OrgBook
    alias: tob-agent
    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      agent_admin_url: $TOB_AGENT_ADMIN_URL

proof_requests:
  greenlight_registration:
    version: '1.0.0'
    schemas:
      - key:
          did: 6qnvgJtqwK44D8LFYnV5Yf
          name: Registered Corporation
          version: '1.0.3'
        attributes:
          - corp_num
          - legal_name


### eof ###
